
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    password VARCHAR(60) NOT NULL CHECK (password !=''),
    email VARCHAR(30) UNIQUE CHECK (email !=''),
    created_at timestamp default NOW(),
    role VARCHAR(30) NOT NULL
);
CREATE UNIQUE INDEX email_idx ON users (email);

DROP TABLE IF EXISTS games CASCADE;
CREATE TABLE games(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) UNIQUE NOT NULL CHECK (name !='')
);

DROP TABLE IF EXISTS gameobjects CASCADE;
CREATE TABLE GameObjects(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(30),
    text TEXT,
    status VARCHAR(10) NOT NULL,
    author_id int REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp default NOW(),
    updated_at timestamp  default NOW(),
    game_id int NOT NULL REFERENCES games(id) ON DELETE CASCADE
);


DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message  TEXT,
    post_id int NOT NULL REFERENCES gameobjects(id) ON DELETE CASCADE,
    author_id int REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp default NOW(),
    approved boolean default FALSE
);


INSERT INTO users(password, email, role) VALUES('$2a$10$57EGRRpGPyW90AMomaCDseu0tYu5Q4AwXygxwV.xIfAKRrdY1QSuW', 'admin', 'ADMIN');
INSERT INTO users(password, email, role) VALUES('$2a$10$7FDRU28UYDswJH3a.8OVeeGnjFxtI9Hj.lvcXggn4BIgFotABpr36', 'trader', 'TRADER');
INSERT INTO users(password, email, role) VALUES('$2a$10$jeNlzzlGt6XSWT0VwCgQs.gsO/QLWj8/v/1cPbByw1egbThtHfhU2', 'user', 'USER');

INSERT INTO games(name) VALUES('CS:GO');
INSERT INTO games(name) VALUES('Fifa');
INSERT INTO games(name) VALUES('Dota');
INSERT INTO games(name) VALUES('Team Fortress');
