
TRUNCATE users CASCADE

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    password VARCHAR(60) NOT NULL CHECK (password !=''),
    email VARCHAR(30) UNIQUE CHECK (email !=''),
    created_at timestamp default NOW(),
    role VARCHAR(10) NOT NULL
);
CREATE UNIQUE INDEX email_idx ON users (email);

DROP TABLE IF EXISTS games CASCADE;
CREATE TABLE games(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) UNIQUE NOT NULL CHECK (name !='')
);

DROP TABLE IF EXISTS gameobjects;
CREATE TABLE GameObjects(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(30),
    text TEXT,
    status VARCHAR(10) NOT NULL,
    author_id int REFERENCES users(id),
    created_at timestamp default NOW(),
    updated_at timestamp  default NOW(),
    game_id int REFERENCES games(id) NOT NULL
);


DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message TEXT,
    post_id int REFERENCES gameobjects(id) NOT NULL,
    author_id int REFERENCES users(id),
    created_at timestamp default NOW(),
    approved boolean NOT NULL
);



INSERT INTO users(password, email, role) VALUES('$2a$12$LpuF1.ErVfiqPOc/Jux.Q.OsrJo7dxgb7fTg0IK3Y/fMjHQ6kxHFa', 'admin', 'ADMIN');


INSERT INTO games(name) VALUES('CS:GO');
INSERT INTO games(name) VALUES('Fifa');
INSERT INTO games(name) VALUES('Dota');
INSERT INTO games(name) VALUES('Team Fortress');
